import { EditorThemeClasses } from "lexical"
import "./rich-editor-theme.css"

const RichEditorTheme: EditorThemeClasses = {
  autocomplete: "editor__autocomplete",
  blockCursor: "editor__blockCursor",
  characterLimit: "editor__characterLimit",
  code: "editor__code",
  codeHighlight: {
    atrule: "editor__tokenAttr",
    attr: "editor__tokenAttr",
    boolean: "editor__tokenProperty",
    builtin: "editor__tokenSelector",
    cdata: "editor__tokenComment",
    char: "editor__tokenSelector",
    class: "editor__tokenFunction",
    "class-name": "editor__tokenFunction",
    comment: "editor__tokenComment",
    constant: "editor__tokenProperty",
    deleted: "editor__tokenDeleted",
    doctype: "editor__tokenComment",
    entity: "editor__tokenOperator",
    function: "editor__tokenFunction",
    important: "editor__tokenVariable",
    inserted: "editor__tokenInserted",
    keyword: "editor__tokenAttr",
    namespace: "editor__tokenVariable",
    number: "editor__tokenProperty",
    operator: "editor__tokenOperator",
    prolog: "editor__tokenComment",
    property: "editor__tokenProperty",
    punctuation: "editor__tokenPunctuation",
    regex: "editor__tokenVariable",
    selector: "editor__tokenSelector",
    string: "editor__tokenSelector",
    symbol: "editor__tokenProperty",
    tag: "editor__tokenProperty",
    unchanged: "editor__tokenUnchanged",
    url: "editor__tokenOperator",
    variable: "editor__tokenVariable",
  },
  embedBlock: {
    base: "editor__embedBlock",
    focus: "editor__embedBlockFocus",
  },
  hashtag: "editor__hashtag",
  heading: {
    h1: "editor__h1",
    h2: "editor__h2",
    h3: "editor__h3",
    h4: "editor__h4",
    h5: "editor__h5",
    h6: "editor__h6",
  },
  hr: "editor__hr",
  hrSelected: "editor__hrSelected",
  image: "editor-image",
  indent: "editor__indent",
  layoutContainer: "editor__layoutContainer",
  layoutItem: "editor__layoutItem",
  link: "editor__link",
  list: {
    checklist: "editor__checklist",
    listitem: "editor__listItem",
    listitemChecked: "editor__listItemChecked",
    listitemUnchecked: "editor__listItemUnchecked",
    nested: {
      listitem: "editor__nestedListItem",
    },
    olDepth: [
      "editor__ol1",
      "editor__ol2",
      "editor__ol3",
      "editor__ol4",
      "editor__ol5",
    ],
    ul: "editor__ul",
  },
  mark: "editor__mark",
  markOverlap: "editor__markOverlap",
  paragraph: "editor__paragraph",
  quote: "editor__quote",
  ruby: "editor__ruby",
  specialText: "editor__specialText",
  tab: "editor__tabNode",
  table: "editor__table",
  tableAddColumns: "editor__tableAddColumns",
  tableAddRows: "editor__tableAddRows",
  tableAlignment: {
    center: "editor__tableAlignmentCenter",
    right: "editor__tableAlignmentRight",
  },
  tableCell: "editor__tableCell",
  tableCellActionButton: "editor__tableCellActionButton",
  tableCellActionButtonContainer: "editor__tableCellActionButtonContainer",
  tableCellHeader: "editor__tableCellHeader",
  tableCellResizer: "editor__tableCellResizer",
  tableCellSelected: "editor__tableCellSelected",
  tableFrozenColumn: "editor__tableFrozenColumn",
  tableFrozenRow: "editor__tableFrozenRow",
  tableRowStriping: "editor__tableRowStriping",
  tableScrollableWrapper: "editor__tableScrollableWrapper",
  tableSelected: "editor__tableSelected",
  tableSelection: "editor__tableSelection",
  tableStickyScrollbar: "editor__tableStickyScrollbar",
  text: {
    bold: "editor__textBold",
    capitalize: "editor__textCapitalize",
    code: "editor__textCode",
    highlight: "editor__textHighlight",
    italic: "editor__textItalic",
    lowercase: "editor__textLowercase",
    strikethrough: "editor__textStrikethrough",
    subscript: "editor__textSubscript",
    superscript: "editor__textSuperscript",
    underline: "editor__textUnderline",
    underlineStrikethrough: "editor__textUnderlineStrikethrough",
    uppercase: "editor__textUppercase",
  },
}

export default RichEditorTheme
